Repository pulp/pulpcore, pull requests merged in 2019-05, with the labels that each got.

#118 Distributions serve RepositoryVersion
  docs/glossary.rst
  docs/installation/configuration.rst
  docs/workflows/exposing-content.rst
  docs/workflows/index.rst
  pulpcore/app/migrations/0001_initial.py
  pulpcore/app/models/publication.py
  pulpcore/app/serializers/publication.py
  pulpcore/app/serializers/repository.py
  pulpcore/content/handler.py
  pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py
  pulpcore/tests/functional/api/using_plugin/test_content_app.py
Labels: breaking-changes, enhancement

#124 Split Distribution into two objects
  docs/release-notes/pulpcore/3.0.x.rst
  pulpcore/app/migrations/0001_initial.py
  pulpcore/app/models/__init__.py
  pulpcore/app/models/publication.py
  pulpcore/app/serializers/__init__.py
  pulpcore/app/serializers/publication.py
  pulpcore/app/viewsets/__init__.py
  pulpcore/app/viewsets/publication.py
  pulpcore/content/handler.py
  pulpcore/tests/functional/api/using_plugin/test_crd_publications.py
  pulpcore/tests/unit/serializers/test_repository.py
Labels: breaking-changes

#135 Problem: REST API does not accept null for string values
  docs/release-notes/pulpcore/3.0.x.rst
  pulpcore/app/models/progress.py
  pulpcore/app/models/repository.py
  pulpcore/app/serializers/content.py
  pulpcore/app/serializers/progress.py
  pulpcore/app/serializers/publication.py
  pulpcore/app/serializers/repository.py
Labels: breaking-changes, bug

#152 Fix serialization of repository field on Publications
  pulpcore/app/serializers/publication.py
Labels: bug
