Repository pulp/pulpcore, pull requests merged in 2020-03, with the labels that each got.

#573 Handle no-previous-version case in remove_duplicates util
  pulpcore/plugin/repo_version_utils.py
Labels: Needs Cherry Pick

#578 Bumps dynaconf max version to < 4.0
  CHANGES/6244.misc
  setup.py
Labels: Needs Cherry Pick, dependencies

#605 Clear up a misleading line re: database support
  CHANGES/6384.doc
  docs/installation/instructions.rst
  docs/settings.rst
Labels: Needs Cherry Pick

#608 Ignores secret fields if the incoming value is the sha256 checksum of…
  CHANGES/6402.bugfix
  pulpcore/app/serializers/fields.py
Labels: Needs Cherry Pick

#614 Problem: Trailing underscores in branch names breaks CI
  .travis/install.sh
Labels: Needs Cherry Pick

#616 Upload chunks to a local file system
  CHANGES/6253.bugfix
  CHANGES/6253.feature
  docs/workflows/upload-publish.rst
  pulpcore/app/migrations/0024_use_local_storage_for_uploads.py
  pulpcore/app/models/upload.py
  pulpcore/app/settings.py
  pulpcore/app/viewsets/upload.py
  pulpcore/tests/functional/api/test_upload.py
Labels: Needs Cherry Pick

#617 Allow tasks to spawn other tasks
  CHANGES/6282.feature
  CHANGES/plugin_api/6270.bugfix
  CHANGES/plugin_api/6282.feature
  pulpcore/app/migrations/0025_task_parent_task.py
  pulpcore/app/models/task.py
  pulpcore/app/serializers/task.py
  pulpcore/app/viewsets/task.py
  pulpcore/tasking/tasks.py
  pulpcore/tests/functional/api/using_plugin/test_tasks.py
Labels: Work In Progress

#619 Problem: Pulp containers do not allow commands like "/bin/bash"
  CHANGES/6420.bugfix
  containers/images/pulp/container-assets/pulp-common-entrypoint.sh
Labels: Needs Cherry Pick
