Repository pulp/pulpcore, pull requests merged in 2022-10, with the labels that each got.

#3188 Fixes #3187 - Fs exporter correctly handles hardlink across partitions
  CHANGES/1949.bugfix
  CHANGES/3187.bugfix
  pulpcore/app/tasks/export.py
Labels: backport-3.17, backport-3.16, backport-3.18, backport-3.19, backport-3.20, backport-3.21

#3286 Addressed another deadlock-window in overlapping-content-syncs path.
  CHANGES/3284.bugfix
  pulpcore/plugin/stages/content_stages.py
Labels: backport-3.16, backport-3.18, backport-3.21

#3348 Fixed the content disposition header for content served from Azure
  CHANGES/3342.bugfix
  pulpcore/content/handler.py
Labels: backport-3.21
