Repository pulp/pulpcore, pull requests merged in 2022-04, with the labels that each got.

#2478 Fixed rare bulk_update() deadlock in ContentSaver.
  CHANGES/2430.bugfix
  pulpcore/plugin/stages/content_stages.py
Labels: backport-3.14, backport-3.17, backport-3.15, backport-3.16, backport-3.18

#2505 Bump django requirement
  requirements.txt
Labels: backport-3.17, backport-3.15, backport-3.16, backport-3.18

#2507 Fix a bug where workers miss notifications
  CHANGES/2506.bugfix
  pulpcore/tasking/pulpcore_worker.py
Labels: backport-3.14, backport-3.17, backport-3.15, backport-3.16, backport-3.18

#2497 Loosened import version-restriction to x.y instead of x.y.z.
  CHANGES/2269.bugfix
  docs/workflows/import-export.rst
  pulpcore/app/tasks/importer.py
  pulpcore/tests/unit/test_import_checks.py
Labels: Katello, BZ, backport-3.17, backport-3.16, backport-3.18

#2541 Improved reason error message for PathNotResolved.
  pulpcore/content/handler.py
Labels: backport-3.19

#2558 Fix does_batch for resolved content
  CHANGES/2557.bugfix
  pulpcore/plugin/stages/models.py
Labels: backport-3.17, backport-3.16, backport-3.18, backport-3.19

#2571 Ensure download has fresh file on retry
  CHANGES/2576.bugfix
  pulpcore/download/http.py
Labels: backport-3.14, backport-3.17, backport-3.15, backport-3.16, backport-3.18, backport-3.19

#2602 Ensure download retry fix occurs for all http subclasses
  pulpcore/download/http.py
Labels: backport-3.14, backport-3.17, backport-3.15, backport-3.16, backport-3.18, backport-3.19
