Repository pulp/pulpcore, pull requests merged in 2022-02, with the labels that each got.

#2184 Fix canceling tasks never being picked up
  CHANGES/2183.bugfix
  pulpcore/tasking/pulpcore_worker.py
Labels: backport-3.14, backport-3.17

#2159 Fixed touch() deadlock window.
  CHANGES/2157.bugfix
  pulpcore/app/models/content.py
Labels: backport-3.14

#2230 Teach touch() to use std Django and remove raw-sql exec.
  CHANGES/2229.bugfix
  pulpcore/app/models/content.py
Labels: backport-3.14, backport-3.17, backport-3.15, backport-3.16
