Repository pulp/pulpcore, pull requests merged in 2022-08, with the labels that each got.

#3031 Serialize orphan cleanup tasks to prevent them from getting in each other's way
  CHANGES/3030.bugfix
  pulpcore/app/views/orphans.py
  pulpcore/app/viewsets/orphans.py
Labels: backport-3.17, backport-3.15, backport-3.16, backport-3.18, backport-3.19, backport-3.20

#3032 Do not dispatch telemetry tasks for production systems.
  .github/template_gitref
  .github/workflows/scripts/install.sh
  .github/workflows/scripts/script.sh
  CHANGES/3015.bugfix
  pulpcore/app/apps.py
  pulpcore/app/tasks/telemetry.py
  pulpcore/app/util.py
Labels: backport-3.20

#3126 Move telemetry setup to pulpcore-worker startup
  CHANGES/3122.bugfix
  pulpcore/app/apps.py
  pulpcore/app/util.py
  pulpcore/tasking/pulpcore_worker.py
Labels: backport-3.20

#3112 Reworked content_stages bulk_update() deadlock fix.
  CHANGES/3111.bugfix
  pulpcore/plugin/stages/content_stages.py
Labels: backport-3.14, backport-3.16, backport-3.18
