Repository pulp/pulpcore, pull requests merged in 2022-07, with the labels that each got.

#2913 Fix usage of gpghome fixture
  .github/template_gitref
  .github/workflows/release.yml
  .github/workflows/scripts/script.sh
  pulpcore/tests/functional/gpg_ascii_armor_signing_service.py
Labels: backport-3.20

#2915 Rename the fixture to better describe its meaning
  pulpcore/tests/functional/__init__.py
  pulpcore/tests/functional/gpg_ascii_armor_signing_service.py
Labels: backport-3.20

#2965 Configure aiohttp to not rewrite redirect URLs
  CHANGES/2964.bugfix
  pulpcore/download/factory.py
  pulpcore/download/http.py
Labels: BZ, backport-3.14, backport-3.17, Bugfix, backport-3.16, backport-3.18, backport-3.19, backport-3.20

#2951 Use published relative paths for FS Exporter
  CHANGES/2933.bugfix
  pulpcore/app/tasks/export.py
Labels: backport-3.16

#3017 Rename fixture admin_user to pulp_admin_user
  pulpcore/tests/functional/__init__.py
Labels: backport-3.20
