Repository pulp/pulpcore, pull requests merged in 2022-03, with the labels that each got.

#2264 Harden operations around repo versions
  CHANGES/2268.bugfix
  pulpcore/app/models/repository.py
Labels: backport-3.17, backport-3.18

#2261 Fix delete repository version causing "duplicate key" error
  CHANGES/2047.bugfix
  CHANGES/2267.bugfix
  pulpcore/app/models/repository.py
  pulpcore/tests/conftest_pulp_file.py
  pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
Labels: backport-3.17, backport-3.16, backport-3.18

#2297 Fix delete repository version causing "duplicate key" error
  CHANGES/2047.bugfix
  CHANGES/2267.bugfix
  pulpcore/app/models/repository.py
  pulpcore/tests/conftest.py
  pulpcore/tests/conftest_pulp_file.py
  pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
Labels: backport-3.16

#2295 Fix new-task-system migration to clean up task and taskreservedresource.
  CHANGES/2101.bugfix
  pulpcore/app/migrations/0064_add_new_style_task_columns.py
Labels: backport-3.14, backport-3.17, backport-3.15, backport-3.16, backport-3.18

#2338 Reduces queue size between stages from 1000 to 1
  CHANGES/2069.bugfix
  CHANGES/plugin_api/2069.bugfix
  pulpcore/plugin/stages/api.py
Labels: backport-3.14, backport-3.17, backport-3.15, backport-3.16, backport-3.18

#2333 Fix a migration mistake resulting in improperly encrypted remote fields
  CHANGES/2327.bugfix
  pulpcore/app/management/commands/datarepair-2327.py
  pulpcore/app/migrations/0073_encrypt_remote_fields.py
Labels: backport-3.17, backport-3.15, backport-3.16, backport-3.18

#2382 Fixes RemoteArtifact duplicate key error
  CHANGES/2381.bugfix
  pulpcore/plugin/stages/artifact_stages.py
Labels: backport-3.14, backport-3.17, backport-3.15, backport-3.16, backport-3.18

#2396 Pin redis on pulpcore < 3.17
  requirements.txt
Labels: backport-3.14, backport-3.15

#2421 Taught ArtifactSaver to order artifacts prior to attempting bulk-create.
  CHANGES/2420.bugfix
  pulpcore/plugin/stages/artifact_stages.py
Labels: backport-3.14, backport-3.17, backport-3.15, backport-3.16, backport-3.18
