Repository pulp/pulpcore, pull requests merged in 2023-09, with the labels that each got.

#4352 Ensure monkeypatch is properly loaded
  CHANGES/4351.bugfix
  pulpcore/app/tasks/export.py
Labels: backport-3.18, backport-3.21, backport-3.22, backport-3.23, backport-3.28, backport-3.32

#4361 Fix encrypted fields bulk_update corrupting data
  CHANGES/4359.bugfix
  pulpcore/app/models/fields.py
  pulpcore/tests/unit/models/test_remote.py
Labels: backport-3.23, backport-3.28, backport-3.32

#4373 Marked repository delete as unsafe for immetiate
  CHANGES/4372.bugfix
  docs/plugin_dev/plugin-writer/concepts/index.rst
  pulpcore/app/viewsets/base.py
  pulpcore/app/viewsets/exporter.py
  pulpcore/app/viewsets/repository.py
Labels: backport-3.28, backport-3.32

#4412 Ensure that non-chunked exports also use compressionlevel=1
  CHANGES/4411.bugfix
  pulpcore/app/tasks/export.py
Labels: backport-3.16, backport-3.18, backport-3.21, backport-3.22, backport-3.23, backport-3.28, backport-3.34

#4479 Fix return value of get_users_with_perms_attached_roles
  CHANGES/4478.bugfix
  pulpcore/app/role_util.py
  pulpcore/tests/unit/roles/test_roles.py
Labels: backport-3.18, backport-3.21, backport-3.22, backport-3.23, backport-3.28, backport-3.35

#4491 [3.22] Backport task profiling functionality
  CHANGES/4436.misc
  dev_requirements.txt
  docs/plugin_dev/plugin-writer/concepts/tasks/diagnostics.rst
  pulpcore/tasking/pulpcore_worker.py
Labels: backport-3.16, backport-3.18, backport-3.21

#4483 Optimize export_artifacts hot loop
  pulpcore/app/importexport.py
Labels: backport-3.16, backport-3.18, backport-3.21, backport-3.22, backport-3.28

#4494 Avoid automatic encoding for fixture server
  pulpcore/tests/functional/utils.py
Labels: backport-3.28, backport-3.35
