Repository pulp/pulpcore, pull requests merged in 2023-12, with the labels that each got.

#4832 Fix async tests using unsafe fixtures
  pulpcore/tests/unit/stages/test_stages.py
Labels: backport-3.18, backport-3.21, backport-3.22, backport-3.23, backport-3.39, backport-3.42

#4815 Fixes repository version repair API for non-default domains.
  CHANGES/4776.bugfix
  CHANGES/4806.bugfix
  pulpcore/app/tasks/repository.py
  pulpcore/tests/functional/api/pulp_file/test_domains.py
  pulpcore/tests/functional/api/using_plugin/test_repair.py
Labels: backport-3.23, backport-3.39, backport-3.43

#4792 Fix division-by-zero on import
  CHANGES/4777.bugfix
  pulpcore/app/serializers/exporter.py
  pulpcore/app/tasks/export.py
  pulpcore/app/tasks/importer.py
Labels: backport-3.39, backport-3.43
