Repository pulp/pulpcore, pull requests merged in 2023-08, with the labels that each got.

#4224 Sets ca_cert for replication remotes.
  CHANGES/4219.bugfix
  pulpcore/app/replica.py
  pulpcore/app/tasks/replica.py
Labels: backport-3.23, backport-3.28, backport-3.29

#4251 Fixed content-handler response-headers/object-storage collision.
  CHANGES/4028.bugfix
  pulpcore/constants.py
  pulpcore/content/handler.py
Labels: backport-3.28, backport-3.29

#4275 Enhance get_content() by omitting the version_membership lookup
  CHANGES/3969.bugfix
  pulpcore/app/models/repository.py
Labels: backport-3.21, backport-3.22, backport-3.23, backport-3.28

#4322 Handle existing labels in migration 0104
  CHANGES/4319.bugfix
  pulpcore/app/migrations/0104_delete_label.py
Labels: backport-3.22, backport-3.23, backport-3.28, backport-3.30
