Repository pulp/pulpcore, pull requests merged in 2023-11, with the labels that each got.

#4645 Fixed how Distribtuion.content_handler() is called.
  CHANGES/plugin_api/4644.bugfix
  pulpcore/content/handler.py
Labels: backport-3.40

#4655 Fix content handler failing to find published/content artifacts for index pages
  CHANGES/plugin_api/4654.bugfix
  pulpcore/content/handler.py
Labels: backport-3.40

#4682 Restore the ability to set --max-requests-jitter
  CHANGES/4679.bugfix
  pulpcore/app/entrypoint.py
  pulpcore/content/entrypoint.py
Labels: backport-3.40, backport-3.39

#4723 Fix pulp_file package name in status
  CHANGES/4724.bugfix
  pulp_file/app/__init__.py
Labels: backport-3.41

#4731 Use new fixture signing key
  pulpcore/tests/functional/gpg_ascii_armor_signing_service.py
Labels: backport-3.18, backport-3.21, backport-3.22, backport-3.23, backport-3.39, backport-3.41
