Repository pulp/pulpcore, pull requests merged in 2023-06, with the labels that each got.

#3886 Taught PulpImport to recover from previously-failed attempt.
  CHANGES/3737.bugfix
  pulpcore/app/tasks/importer.py
Labels: backport-3.18, backport-3.21, backport-3.22

#3904 Do not cast objects when initializing their string representation
  CHANGES/3898.bugfix
  pulpcore/app/models/base.py
Labels: backport-3.27

#3884 Use a more appropriate compression level for exports
  CHANGES/3869.bugfix
  pulpcore/app/monkeypatch.py
  pulpcore/app/tasks/export.py
Labels: backport-3.18, backport-3.21, backport-3.22, backport-3.23

#3947 Defer get_user_model calls to prevent circular imports
  CHANGES/3957.bugfix
  pulpcore/app/models/role.py
  pulpcore/app/role_util.py
Labels: backport-3.27, backport-3.28
