Repository pulp/pulpcore, pull requests merged in 2023-07, with the labels that each got.

#3996 Fix api schema for `upstream_pulps_replicate`
  CHANGES/3995.bugfix
  pulpcore/app/viewsets/replica.py
Labels: backport-3.23, backport-3.28

#3976 Incremental export for file exporter will now include published metadata
  CHANGES/3941.bugfix
  pulpcore/app/tasks/export.py
Labels: backport-3.21, backport-3.22

#4036 Pin importlib-metadata to avoid an unsolvable dependency resolution by pip
  CHANGES/4042.bugfix
  requirements.txt
Labels: backport-3.26, backport-3.27, backport-3.28, backport-3.29

#4052 Incremental Export fix for File/Pass Through publications
  CHANGES/4051.bugfix
  pulpcore/app/tasks/export.py
Labels: backport-3.18, backport-3.21, backport-3.22, backport-3.28, backport-3.29

#4090 Fix a significant memory leak
  CHANGES/2250.bugfix
  pulpcore/app/access_policy.py
Labels: backport-3.18, backport-3.21, backport-3.22, backport-3.23, backport-3.29

#4112 Taught repair task to be tolerant in the face of any artifact downloa…
  CHANGES/4111.bugfix
  pulpcore/app/management/commands/handle-artifact-checksums.py
  pulpcore/app/tasks/repository.py
Labels: backport-3.18, backport-3.21, backport-3.22, backport-3.23, backport-3.29

#4164 Fixes bug where replication would delete repositories across domains
  CHANGES/4158.bugfix
  pulpcore/app/replica.py
  pulpcore/tests/functional/api/test_replication.py
Labels: backport-3.23, backport-3.28, backport-3.29

#4160 Taught import to be able to use less than all-available workers.
  CHANGES/4068.bugfix
  pulpcore/app/settings.py
  pulpcore/app/tasks/importer.py
Labels: backport-3.18, backport-3.21, backport-3.22, backport-3.23, backport-3.28, backport-3.29

#4182 Made reclaim space task more tolerant in the face of artifact shared …
  CHANGES/3610.bugfix
  pulpcore/app/tasks/reclaim_space.py
Labels: backport-3.18, backport-3.21, backport-3.22, backport-3.23, backport-3.28, backport-3.29

#4161 Taught export to insure de-duplicated Artifact.json.
  CHANGES/4159.bugfix
  pulpcore/app/importexport.py
  pulpcore/app/tasks/export.py
Labels: backport-3.18, backport-3.21, backport-3.22, backport-3.23, backport-3.28, backport-3.29

#4211 Reset export to using a set() for Artifacts.
  CHANGES/4210.bugfix
  pulpcore/app/importexport.py
  pulpcore/app/tasks/export.py
Labels: backport-3.18, backport-3.21, backport-3.22, backport-3.23, backport-3.28, backport-3.29
