Repository pulp/pulpcore, pull requests merged in 2023-10, with the labels that each got.

#4517 Minor memory + perf export optimizations
  pulpcore/app/importexport.py
  pulpcore/app/tasks/export.py
Labels: backport-3.16, backport-3.21, backport-3.22, backport-3.23, backport-3.28

#4569 Taught ContentArtifactResource import to cache content results to imp…
  CHANGES/4564.bugfix
  pulpcore/app/modelresource.py
Labels: backport-3.16

#4514 Pin django-storages extra requirements
  setup.py
Labels: backport-3.23, backport-3.28, backport-3.37

#4609 Works around a sync-time performance regression on PG12
  CHANGES/4591.bugfix
  pulpcore/app/models/repository.py
Labels: backport-3.16, backport-3.18, backport-3.21, backport-3.22, backport-3.23, backport-3.28
