Repository pulp/pulpcore, pull requests merged in 2024-11, with the labels that each got.

#5983 Future proof the pulp_file repair tests for python 3.11
  pulpcore/tests/functional/api/using_plugin/test_repair.py
Labels: backport-3.49, no-issue, no-changelog

#5988 Add 3.63 to supported-branches for katello/4.16.
  template_config.yml
Labels: no-issue, no-changelog

#5994 Remove functional tests for opentelemetry instrumentation
  .github/workflows/scripts/install.sh
  .github/workflows/scripts/pre_before_script.sh
  .gitignore
  pulp_file/tests/functional/api/test_telemetry_collection.py
  pulpcore/pytest_plugin.py
  pulpcore/tests/functional/api/test_status.py
  pulpcore/tests/functional/api/test_tasking.py
  pulpcore/tests/functional/assets/otel_server.py
  template_config.yml
Labels: no-issue, no-changelog

#5969 Add cache_key to the plugin api
  CHANGES/plugin_api/cache-key.feature
  pulpcore/plugin/util.py
Labels: no-issue

#5970 Fix cross-domain content assertion
  CHANGES/content-assert.bugfix
  pulpcore/app/models/repository.py
Labels: backport-3.49, backport-3.67, backport-3.63

#5993 Remove functional tests for opentelemetry instrumentation
  .ci/ansible/Containerfile.j2
  .ci/assets/ci_constraints.txt
  .github/template_gitref
  .github/workflows/scripts/install.sh
  .github/workflows/scripts/pre_before_script.sh
  .github/workflows/test.yml
  .gitignore
  pulp_file/tests/functional/api/test_telemetry_collection.py
  pulpcore/tests/functional/api/test_status.py
  pulpcore/tests/functional/assets/otel_server.py
  releasing.md
  template_config.yml
Labels: no-issue, no-changelog

#6007 Finish backporting aiohttp 3.10 bump
  pulpcore/download/factory.py
Labels: backport-3.22, backport-3.39, backport-3.28, no-issue, no-changelog

#5984 Add ClientConnectionError as retriable exception on content-app streaming
  CHANGES/5967.bugfix
  pulpcore/content/handler.py
Labels: backport-3.39, backport-3.49, no-issue, backport-3.63

#6019 Switch from using setup.py to pyproject.toml
  .bumpversion.cfg
  .github/template_gitref
  .github/workflows/scripts/before_install.sh
  MANIFEST.in
  docs/dev/guides/git.md
  docs/dev/guides/plugin-walkthrough.md
  pyproject.toml
  requirements.txt
  setup.py
Labels: no-issue, no-changelog

#5989 Drop 3.21 from supported branches (EOL is 30 nov)
  template_config.yml
Labels: no-issue, no-changelog

#6040 Bump minor version
  .bumpversion.cfg
  .github/template_gitref
  .github/workflows/update_ci.yml
  CHANGES/5941.bugfix
  CHANGES/5967.bugfix
  CHANGES/content-assert.bugfix
  CHANGES/plugin_api/cache-key.feature
  pulp_certguard/app/__init__.py
  pulp_file/app/__init__.py
  pulpcore/app/apps.py
  pyproject.toml
  template_config.yml
Labels: no-issue

#6051 Update CI
  .bumpversion.cfg
  .ci/scripts/check_release.py
  .github/template_gitref
  .github/workflows/scripts/build_python_client.sh
  .github/workflows/scripts/install.sh
  .github/workflows/scripts/publish_client_pypi.sh
  .github/workflows/test.yml
  .github/workflows/update_ci.yml
  pyproject.toml
  template_config.yml
Labels: no-issue, no-changelog

#6055 Update CI for branch 3.49
  .bumpversion.cfg
  .ci/scripts/check_release.py
  .github/template_gitref
  .github/workflows/scripts/build_python_client.sh
  .github/workflows/scripts/install.sh
  .github/workflows/scripts/publish_client_pypi.sh
  .github/workflows/test.yml
  .github/workflows/update_ci.yml
  pyproject.toml
  template_config.yml
Labels: no-issue, no-changelog

#6056 Update CI for branch 3.63
  .bumpversion.cfg
  .ci/scripts/check_release.py
  .github/template_gitref
  .github/workflows/scripts/build_python_client.sh
  .github/workflows/scripts/install.sh
  .github/workflows/scripts/publish_client_pypi.sh
  .github/workflows/test.yml
  .github/workflows/update_ci.yml
  pyproject.toml
  template_config.yml
Labels: no-issue, no-changelog

#6060 Update CONTRIBUTING.md docs link
  CONTRIBUTING.md
Labels: no-issue, no-changelog

#5939 Expose json dict field plugin api
  CHANGES/plugin_api/+expose-json-dict.misc
  pulpcore/app/serializers/__init__.py
  pulpcore/app/serializers/fields.py
  pulpcore/plugin/serializers/__init__.py
  pulpcore/tests/unit/serializers/test_fields.py
Labels: no-issue

#6063 [PULP-205] Allow multiple bind addresses on entrypoints
  CHANGES/6053.bugfix
  pulpcore/app/entrypoint.py
  pulpcore/content/entrypoint.py
Labels: backport-3.49, backport-3.63, backport-3.68

#6090 Backport #5658 to 3.49
  pulpcore/app/settings.py
  pulpcore/app/tasks/replica.py
  pulpcore/download/factory.py
  requirements.txt
Labels: no-issue, no-changelog
