Repository pulp/pulpcore, pull requests merged in 2024-12, with the labels that each got.

#6100 Always add core version to the api spec
  CHANGES/+core_in_bindings_spec.feature
  pulpcore/openapi/__init__.py
Labels: no-issue

#6087 [PULP-208] Disable download retry with on demand streaming
  CHANGES/5937.bugfix
  pulpcore/content/handler.py
  pulpcore/download/http.py
Labels: no-issue

#6078 Fix GetOrCreateSerializerMixin not working with pulp_domain
  CHANGES/plugin_api/domain-get-create-serializer-mixin.bugfix
  pulpcore/app/serializers/base.py
  pulpcore/tests/unit/serializers/test_base.py
Labels: backport-3.39, backport-3.28, backport-3.49, no-issue, backport-3.63, backport-3.68

#6115 Patchback/backports/3.49/0ca3caee13e919c04aacefac333de97b383b7120/pr 5490
  requirements.txt
Labels: no-issue, no-changelog

#6064 [SAT-29018] Fix/corrupted RA blocks content streaming
  CHANGES/5725.bugfix
  pulp_file/pytest_plugin.py
  pulp_file/tests/functional/api/test_acs.py
  pulpcore/app/migrations/0126_remoteartifact_failed_at.py
  pulpcore/app/models/content.py
  pulpcore/app/settings.py
  pulpcore/content/handler.py
  pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
  pulpcore/tests/functional/utils.py
Labels: no-issue

#6141 Update update dependencies to prevent downgrades from 3.49
  requirements.txt
Labels: no-issue, no-changelog

#6143 Update aiohttp dependency to 3.10.11
  requirements.txt
Labels: no-issue, no-changelog

#6142 Update aiohttp dependency to 3.10.11
  requirements.txt
Labels: no-issue, no-changelog
