Repository pulp/pulpcore, pull requests merged in 2024-04, with the labels that each got.

#5011 Improves the `download_content_unit` test fixture.
  .github/workflows/scripts/install.sh
  CHANGES/5010.misc
  pulpcore/tests/functional/__init__.py
  template_config.yml
Labels: backport-3.50

#5231 Rewrite some of the import/export test fixtures for more flexibility
  pulpcore/tests/functional/api/using_plugin/test_pulpimport.py
Labels: backport-3.39, backport-3.45, backport-3.50, backport-3.49

#5245 Fix creation hooks being called for Upload
  CHANGES/5199.bugfix
  pulpcore/app/models/upload.py
  pulpcore/tests/functional/__init__.py
  pulpcore/tests/functional/api/test_upload.py
Labels: backport-3.50

#5272 Stop failing the post_create hooks with no viewset
  CHANGES/plugin_api/5267.bugfix
  pulpcore/app/models/access_policy.py
  pulpcore/tests/unit/models/test_base.py
Labels: backport-3.51

#5274 Allow gunicorn/22.0.0 to pick up gunicorn security fixes.
  requirements.txt
Labels: backport-3.22, backport-3.39, backport-3.28, backport-3.49, backport-3.51

#5281 Added csrf_token passing to django optional_logout
  CHANGES/5250.bugfix
  pulpcore/app/templates/rest_framework/api.html
Labels: backport-3.51

#5312 Fix RequireVersion missing backwards methods
  pulpcore/migrations.py
Labels: backport-3.39, backport-3.49, backport-3.52
