Repository pulp/pulpcore, pull requests merged in 2024-05, with the labels that each got.

#5365 Stop task cleanup to delete Contents and Artifacts
  CHANGES/5363.bugfix
  pulpcore/tasking/_util.py
Labels: backport-3.21, backport-3.22, backport-3.39, backport-3.28, backport-3.49, backport-3.53

#5382 Update ci_update_docs setting to true.
  doc_requirements.txt
  docs/Makefile
  docs/conf.py
  docs/static/.gitkeep
  docs/template_gitref
  template_config.yml
Labels: backport-3.21, backport-3.22

#5388 Fix large exports failing
  CHANGES/5375.bugfix
  pulpcore/app/importexport.py
  pulpcore/app/tasks/export.py
Labels: backport-3.39, backport-3.49
