Repository pulp/pulpcore, pull requests merged in 2024-06, with the labels that each got.

#5443 Pin the pytest-redis requirement for unit tests
  unittest_requirements.txt
Labels: backport-3.21, backport-3.22, backport-3.39, backport-3.28, backport-3.49, backport-3.54

#5463 Add openapi command to pulpcore-manager
  CHANGES/5462.feature
  pulpcore/app/checks.py
  pulpcore/app/management/commands/openapi.py
  pulpcore/app/settings.py
  pulpcore/tests/unit/test_settings.py
Labels: backport-3.54

#5475 Add openapi command to pulpcore-manager
  CHANGES/5462.misc
  pulpcore/app/checks.py
  pulpcore/app/management/commands/openapi.py
  pulpcore/app/settings.py
  pulpcore/tests/unit/test_settings.py
  unittest_requirements.txt
Labels: backport-3.21, backport-3.22

#5476 Add openapi command to pulpcore-manager
  CHANGES/5462.misc
  pulpcore/app/checks.py
  pulpcore/app/management/commands/openapi.py
  pulpcore/app/settings.py
  requirements.txt
  setup.py
Labels: backport-3.21

#5479 Backport the api doc component logic
  pulpcore/openapi/__init__.py
Labels: backport-3.21, backport-3.22, backport-3.28

#5452 Artifacts are unique per domain.
  pulpcore/app/models/domain.py
  pulpcore/app/util.py
Labels: backport-3.49

#5465 Replica - stop assuming every plugin supports publications
  CHANGES/5464.bugfix
  pulpcore/app/replica.py
Labels: backport-3.49, backport-3.54

#5485 Backport the api doc component logic
  pulpcore/openapi/__init__.py
Labels: backport-3.21

#5511 Add a sentinal value to CONTENT_ORIGIN
  CHANGES/5510.bugfix
  pulpcore/app/checks.py
  pulpcore/app/settings.py
Labels: backport-3.21, backport-3.22, backport-3.39, backport-3.28, backport-3.49, backport-3.55
