Repository pulp/pulpcore, pull requests merged in 2024-10, with the labels that each got.

#5839 Make the kafka producer an optional dependency
  CHANGES/5850.bugfix
  pulpcore/tasking/kafka.py
  pulpcore/tasking/tasks.py
  requirements.txt
  setup.py
Labels: no-issue

#5858 Collect artifact size metrics after caching the content
  CHANGES/5817.bugfix
  pulpcore/cache/cache.py
  pulpcore/content/handler.py
  pulpcore/metrics.py
Labels: backport-3.63

#5889 Remove the outdated information from the docs
  docs/dev/guides/record-a-demo.md
  docs/dev/guides/release_process.md
  pulp_file/app/viewsets.py
  pulp_file/docs/admin/guides/rbac.md
  pulpcore/app/viewsets/access_policy.py
Labels: no-issue, no-changelog

#5890 [noissue]: Update psycopg[binary] requirement
  requirements.txt
Labels: no-issue, no-changelog

#5893 Fix misformated changelog titles
  CHANGES.md
Labels: no-issue, no-changelog

#5896 Fix scheduled task purge failing without user
  CHANGES/5881.bugfix
  pulpcore/app/tasks/purge.py
Labels: backport-3.65

#5891 Re-enable Storage Metrics emiter and refactor it.
  CHANGES/5762.feature
  pulpcore/app/models/domain.py
  pulpcore/app/tasks/telemetry.py
  pulpcore/app/util.py
  pulpcore/app/wsgi.py
  pulpcore/tasking/_util.py
Labels: no-issue

#5910 fix: Signing scripts needs access to environment variables.
  CHANGES/5911.bugfix
  pulpcore/app/models/content.py
Labels: backport-3.49

#5919 Backport Update pulp-glue requirement from <0.29,>=0.18.0 to >=0.18.0,<0.30
  .github/workflows/scripts/install.sh
  requirements.txt
  template_config.yml
Labels: no-issue, no-changelog

#5925 Add rebasemigration as a management command
  pulpcore/app/management/commands/migrationstat.py
  pulpcore/app/management/commands/rebasemigrations.py
Labels: no-issue, no-changelog

#5938 [3.63] Fix Any serializer type regression breaking Ruby bindings
  CHANGES/+fix-any-type.bugfix
  pulpcore/app/serializers/domain.py
  pulpcore/app/serializers/exporter.py
  pulpcore/app/serializers/fields.py
  pulpcore/app/serializers/importer.py
  pulpcore/app/serializers/task.py
Labels: no-issue

#5936 Fix Any serializer type regression breaking Ruby bindings
  CHANGES/+fix-any-type.bugfix
  pulpcore/app/serializers/domain.py
  pulpcore/app/serializers/exporter.py
  pulpcore/app/serializers/fields.py
  pulpcore/app/serializers/importer.py
  pulpcore/app/serializers/task.py
Labels: backport-3.21, backport-3.22, backport-3.39, backport-3.28, backport-3.49, no-issue, backport-3.66

#5935 Ensure users can not add cross-domain content through modify endpoint
  CHANGES/5934.bugfix
  pulp_file/tests/functional/api/test_domains.py
  pulpcore/app/models/repository.py
  pulpcore/app/serializers/base.py
  pulpcore/app/util.py
Labels: backport-3.39, backport-3.28, backport-3.49, backport-3.66, backport-3.63

#5952 [PR #5936/58425d79 backport][3.22] Fix Any serializer type regression breaking Ruby bindings
  CHANGES/+fix-any-type.bugfix
  pulpcore/app/serializers/exporter.py
  pulpcore/app/serializers/fields.py
  pulpcore/app/serializers/importer.py
  pulpcore/app/serializers/task.py
Labels: no-issue

#5951 [PR #5936/58425d79 backport][3.21] Fix Any serializer type regression breaking Ruby bindings
  CHANGES/+fix-any-type.bugfix
  pulpcore/app/serializers/exporter.py
  pulpcore/app/serializers/fields.py
  pulpcore/app/serializers/importer.py
  pulpcore/app/serializers/task.py
Labels: no-issue

#5955 Allow aiohttp <3.10.11
  requirements.txt
Labels: backport-3.21, backport-3.22, backport-3.39, backport-3.28, no-issue, no-changelog

#5958 Allow aiohttp <3.10.11
  pulpcore/tests/unit/download/test_factory.py
  requirements.txt
Labels: backport-3.21, no-issue, no-changelog

#5942 Cache a local copy of the signing key for local testing
  .gitignore
  pulpcore/pytest_plugin.py
Labels: no-issue, no-changelog

#5961 Allow aiohttp <3.10.11
  pulpcore/tests/unit/download/test_factory.py
  requirements.txt
Labels: no-issue, no-changelog

#5962 Remove functional tests for opentelemetry instrumentation
  .github/workflows/scripts/install.sh
  .github/workflows/scripts/pre_before_script.sh
  .gitignore
  pulp_file/tests/functional/api/test_telemetry_collection.py
  pulpcore/pytest_plugin.py
  pulpcore/tests/functional/api/test_status.py
  pulpcore/tests/functional/api/test_tasking.py
  pulpcore/tests/functional/assets/otel_server.py
  template_config.yml
Labels: no-issue, no-changelog

#5959 Document S3 operations that the AWS access key must be able to perform
  docs/user/guides/create-domains.md
Labels: no-issue, no-changelog
