Repository pulp/pulpcore, pull requests merged in 2024-07, with the labels that each got.

#5564 Template fix
  CHANGES/5563.bugfix
  pulpcore/app/templatetags/pulp_urls.py
  pulpcore/tests/unit/test_pulp_urls.py
Labels: backport-3.21, backport-3.22, backport-3.39, backport-3.28, backport-3.49, backport-3.55

#5608 Bump Dynaconf UB to <3.3.0
  requirements.txt
Labels: backport-3.49, backport-3.55

#5618 Casts a repo object before checking permission
  CHANGES/5619.bugfix
  pulpcore/app/global_access_conditions.py
Labels: backport-3.49, backport-3.55

#5639 Change url field name to avoid plugin conflicts
  CHANGES/plugin_api/5633.bugfix
  pulp_file/tests/functional/api/test_crud_content_unit.py
  pulpcore/plugin/serializers/content.py
Labels: backport-3.56
