Repository pulp/pulpcore, pull requests merged in 2025-09, with the labels that each got.

#6904 Fix deprecation warnings
  pulpcore/app/settings.py
  pulpcore/content/handler.py
  pulpcore/tests/functional/api/test_status.py
  pulpcore/tests/functional/api/test_upload.py
  pulpcore/tests/functional/api/using_plugin/test_distributions.py
  pulpcore/tests/functional/utils.py
  pulpcore/tests/unit/metrics/test_aiohttp_instrumentation.py
  pulpcore/tests/unit/stages/test_artifactdownloader.py
  pulpcore/tests/unit/viewsets/test_viewset_base.py
Labels: no-issue, no-changelog

#6948 Mark all_tasks_dispatched as deprecated
  pulpcore/app/serializers/task.py
Labels: no-issue, no-changelog

#6937 [PULP-553] Enable immediate task execution on content app (1/2)
  pulpcore/app/models/repository.py
  pulpcore/app/models/task.py
  pulpcore/app/tasks/repository.py
  pulpcore/plugin/tasking.py
  pulpcore/tasking/tasks.py
  pulpcore/tests/functional/api/test_tasking.py
  pulpcore/tests/unit/content/test_handler.py
Labels: no-issue, no-changelog

#6950 Fixed the case of "domain enabled but importing into default.
  pulpcore/app/modelresource.py
  pulpcore/app/tasks/importer.py
Labels: no-issue, no-changelog

#6962 Enable immediate task from content app (2/2)
  CHANGES/+task-immediate.misc
  pulpcore/tasking/tasks.py
  pulpcore/tests/unit/content/test_handler.py
Labels: no-issue

#6972 Enabled two import/export tests when domains enabled.
  pulpcore/tests/functional/api/using_plugin/test_filesystemexport.py
  pulpcore/tests/functional/api/using_plugin/test_pulpimport.py
Labels: no-issue, no-changelog

#6976 Always call wakeup_worker in syncronous context
  pulpcore/tasking/tasks.py
Labels: no-issue, no-changelog, backport-3.90

#6949 Change how the exceptions are propagated on the Content instrumentation middleware.
  CHANGES/6925.bugfix
  pulpcore/content/instrumentation.py
Labels: backport-3.39, backport-3.49, no-issue, backport-3.63, backport-3.73, backport-3.90

#6977 Run orphan cleanup periodically
  CHANGES/+orphan.feature
  docs/admin/reference/settings.md
  pulpcore/app/util.py
Labels: no-issue

#6963 [PULP-785] Remove advisory lock from janitorial work
  CHANGES/+janitor_coordination.feature
  pulpcore/app/util.py
  pulpcore/constants.py
  pulpcore/exceptions/__init__.py
  pulpcore/exceptions/base.py
  pulpcore/tasking/worker.py
Labels: no-issue
