Repository pulp/pulpcore, pull requests merged in 2025-07, with the labels that each got.

#6742 Update domains docs
  docs/dev/learn/_SUMMARY.md
  docs/dev/learn/sync_pipeline.md
  docs/user/guides/create-domains.md
Labels: no-issue, no-changelog

#6756 Use glue list_iterator in replicate code
  pulpcore/app/replica.py
  pyproject.toml
Labels: no-issue, no-changelog

#6759 Read a task from db after creating it
  pulpcore/tasking/tasks.py
Labels: no-issue, no-changelog, backport-3.82

#6784 Fix RepositoryVersion.content query failing when >65K units
  CHANGES/6772.bugfix
  pulpcore/app/models/repository.py
Labels: backport-3.83

#6791 Pin azure-storage-blob to fix Azurite issue
  pyproject.toml
Labels: no-issue, no-changelog
