Repository pulp/pulpcore, pull requests merged in 2025-05, with the labels that each got.

#6532 Add memray and pyinstrument as optional dependencies
  pyproject.toml
Labels: no-issue, no-changelog

#6533 Reapply "[PULP-270] Validate and clean comments from Remote certs."
  CHANGES/6510.bugfix
  pulp_file/tests/functional/api/test_remote_settings.py
  pulpcore/app/serializers/repository.py
Labels: no-issue

#6538 Reapply "[PULP-270] Validate and clean comments from Remote certs."
  pulpcore/app/serializers/repository.py
Labels: no-issue, no-changelog

#6539 Reapply "[PULP-270] Validate and clean comments from Remote certs."
  pulpcore/app/serializers/repository.py
Labels: no-issue, no-changelog

#6544 Add uvloop usage as an optional feature on the content-app
  CHANGES/6021.feature
  docs/admin/reference/settings.md
  pulpcore/app/settings.py
  pulpcore/content/__init__.py
  pulpcore/content/entrypoint.py
  pyproject.toml
Labels: no-issue

#6555 Fix test_performance.
  CHANGES/+performance_test.misc
  pulpcore/tests/performance/test_performance.py
Labels: no-issue

#6571 [backport 3.63] Fix wrong downloader session close on on-demand streaming
  pulpcore/content/handler.py
  pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
Labels: no-issue, no-changelog

#6572 [bacport 3.73] Fix wrong downloader session close on on-demand streaming
  pulpcore/content/handler.py
  pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
Labels: no-issue, no-changelog

#6573 [backport 3.77] Fix wrong downloader session close on on-demand streaming
  pulpcore/content/handler.py
  pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
Labels: no-issue, no-changelog

#6586 Resolve Python logger warnings
  pulpcore/app/entrypoint.py
  pulpcore/app/management/commands/dump-publications-to-fs.py
  pulpcore/app/replica.py
  pulpcore/app/serializers/base.py
  pulpcore/app/tasks/repository.py
  pulpcore/tasking/worker.py
Labels: no-issue, no-changelog

#6581 Add the execution time of a task to its finishing log entry.
  CHANGES/6569.feature
  pulpcore/tasking/tasks.py
Labels: no-issue

#6588 Reduce db load on tasks state machine
  pulpcore/app/models/task.py
  pulpcore/app/openpgp.py
Labels: multi-commit, no-issue, no-changelog

#6591 [PULP-549] Bump dependencies
  .github/workflows/scripts/install.sh
  pulpcore/app/tasks/replica.py
  requirements.txt
  template_config.yml
Labels: no-issue, no-changelog

#6597 [PULP-552] Redefine psycopg dependency following semver
  pyproject.toml
Labels: backport-3.49, no-issue, no-changelog, backport-3.63, backport-3.73, backport-3.79

#6601 Redefine psycopg dependency following semver
  requirements.txt
Labels: no-issue, no-changelog

#6600 Redefine psycopg dependency following semver
  requirements.txt
Labels: no-issue, no-changelog

#6590 Deprecate TaskGroup.finish()
  CHANGES/plugin_api/task_group_finish.removal
  docs/dev/learn/subclassing/viewsets.md
  pulp_file/app/viewsets.py
  pulpcore/app/models/task.py
  pulpcore/app/tasks/importer.py
  pulpcore/app/tasks/replica.py
  pulpcore/app/tasks/test.py
Labels: no-issue

#6607 Add vscode to gitignore
  .gitignore
Labels: no-issue, no-changelog
