Repository pulp/pulpcore, pull requests merged in 2025-04, with the labels that each got.

#6425 Pin the aiohttp dependency to semver boundaries.
  .ci/assets/ci_constraints.txt
  .github/workflows/scripts/script.sh
  CHANGES/+aiohttp_semver.bugfix
  functest_requirements.txt
  pyproject.toml
Labels: no-issue, backport-3.73

#6414 Docs fixes
  docs/dev/reference/code-style-guide.md
  docs/dev/tutorials/quickstart-docs.md
Labels: no-issue, no-changelog

#6426 Pin the aiohttp dependency to semver boundaries.
  .ci/assets/ci_constraints.txt
  .github/workflows/scripts/script.sh
  CHANGES/+aiohttp_semver.bugfix
  functest_requirements.txt
  pyproject.toml
Labels: no-issue

#6435 Fix second scenario for on-demand pull-through caching
  CHANGES/+second_ondemand_pullthrough.bugfix
  pulpcore/content/handler.py
  pulpcore/tests/unit/content/test_handler.py
Labels: backport-3.49, no-issue, backport-3.63, backport-3.73, backport-3.75

#6437 [PULP-452] Refactor purge tasks test for resilience
  pulpcore/tests/functional/api/test_task_purge.py
Labels: no-issue, no-changelog

#6428 Set the X-PULP-ARTIFACT-SIZE header at the handle_response_header function.
  CHANGES/6390.bugfix
  pulpcore/content/handler.py
Labels: no-issue

#6446 Revert "Add timeout to immediate task execution"
  CHANGES/plugin_api/+revert-immediate-task-timeout.bugfix
  pulpcore/app/tasks/base.py
  pulpcore/app/tasks/test.py
  pulpcore/app/viewsets/base.py
  pulpcore/constants.py
  pulpcore/pytest_plugin.py
  pulpcore/tasking/tasks.py
  pulpcore/tests/functional/api/test_tasking.py
Labels: no-issue, backport-3.75

#6480 Fix add_roles_for_object_creator handling of AnonymousUser
  CHANGES/plugin_api/+anon-user-object-create.bugfix
  pulpcore/app/models/access_policy.py
Labels: no-issue

#6484 Fix links in developer domain docs
  docs/dev/learn/domains/domains_compatibility.md
Labels: no-issue, no-changelog

#6483 Add the task_name and if it's a task.immediate to the task log entry.
  CHANGES/6482.feature
  pulpcore/tasking/tasks.py
  pulpcore/tasking/worker.py
Labels: no-issue

#6492 [PULP-270] Validate and clean comments from Remote certs.
  CHANGES/6491.bugfix
  pulp_file/tests/functional/api/test_remote_settings.py
  pulpcore/app/serializers/repository.py
Labels: backport-3.22, backport-3.39, backport-3.49, backport-3.63, backport-3.73

#6501 [PULP-239] Fixed a memory issue triggered by ACS usage
  CHANGES/6500.bugfix
  pulpcore/plugin/stages/artifact_stages.py
Labels: backport-3.39, backport-3.49, backport-3.63, backport-3.73, backport-3.76

#6509 Fix docs
  docs/dev/learn/rbac/access_policy.md
Labels: multi-commit, no-issue, no-changelog

#6524 Update deprecated general_update task
  pulpcore/app/replica.py
  pulpcore/app/tasks/__init__.py
  pulpcore/plugin/tasking.py
Labels: no-issue, no-changelog

#6528 Fix WorkerNameMetricsExporter to not export unless otel is enabled.
  CHANGES/6529.bugfix
  pulpcore/app/wsgi.py
Labels: no-issue
