Repository pulp/pulpcore, pull requests merged in 2025-08, with the labels that each got.

#6755 [PULP-705] Bump OpenAPI version
  .github/workflows/scripts/install.sh
  CHANGES/+oasversion.removal
  pulpcore/app/settings.py
  pulpcore/tests/functional/api/test_auth.py
  pulpcore/tests/functional/api/test_openapi_schema.py
  template_config.yml
Labels: no-issue

#6823 Unpin azure-storage-blob
  pyproject.toml
Labels: no-issue, no-changelog

#6612 [PULP-570] Mark a failed heartbeat as a catastrophic failure
  CHANGES/heartbeat.bugfix
  pulpcore/app/entrypoint.py
  pulpcore/app/models/status.py
  pulpcore/content/__init__.py
  pulpcore/tasking/worker.py
  pulpcore/tests/unit/content/test_heartbeat.py
Labels: no-issue

#6833 Fix task's domain info on worker logs
  CHANGES/6818.bugfix
  pulpcore/tasking/worker.py
Labels: no-issue

#6841 Add AppStatus table
  CHANGES/+app_status.feature
  pulpcore/app/entrypoint.py
  pulpcore/app/migrations/0137_appstatus.py
  pulpcore/app/models/__init__.py
  pulpcore/app/models/status.py
  pulpcore/app/models/task.py
  pulpcore/content/__init__.py
  pulpcore/migrations.py
  pulpcore/tasking/worker.py
  pulpcore/tests/unit/content/test_heartbeat.py
Labels: no-issue

#6850 Fix RequiredVersion migration check
  CHANGES/+migration_check.bugfix
  pulpcore/migrations.py
Labels: no-issue, backport-3.85

#6853 Add optimizemigration management command
  pulpcore/app/management/commands/optimizemigration.py
Labels: no-issue, no-changelog

#6857 Remove support for non-async immediate tasks
  CHANGES/plugin_api/+remove-sync-immediate-suport.removal
  pulpcore/tasking/tasks.py
  pulpcore/tests/functional/api/test_tasking.py
Labels: no-issue, backport-3.85

#6846 Add a setting to set the bucket boundaries for the API request duration metric.
  CHANGES/6845.feature
  docs/admin/learn/architecture.md
  pulpcore/app/settings.py
  pulpcore/middleware.py
Labels: no-issue

#6882 Update Azure and S3 storage settings for 3.86
  .ci/ansible/settings.py.j2
  .github/workflows/scripts/install.sh
  template_config.yml
Labels: no-issue, no-changelog
