Repository pulp/pulpcore, pull requests merged in 2025-06, with the labels that each got.

#6648 Extend scope of fixtures
  pulpcore/pytest_plugin.py
  pulpcore/tests/functional/api/test_status.py
Labels: backport-3.49, no-issue, no-changelog, backport-3.63, backport-3.73, backport-3.80

#6654 Patchback/backports/3.63/016174e37b23059b927108b2cd4e1e2e6aee907b/pr 6648
  pulpcore/pytest_plugin.py
  pulpcore/tests/functional/api/test_status.py
Labels: backport-3.49, no-issue, no-changelog

#6658 Update cryptography requirement
  pyproject.toml
Labels: no-issue, no-changelog

#6681 Fix some heuristic about domainized urls
  pulpcore/openapi/__init__.py
Labels: backport-3.63, backport-3.73, backport-3.80

#6697 [3.63] Pin pycares to avoid bug with aiodns combination
  requirements.txt
Labels: backport-3.39, backport-3.28, backport-3.49, no-issue, no-changelog

#6696 [3.73] Pin pycares to avoid bug with aiodns combination
  pyproject.toml
Labels: no-issue, no-changelog

#6698 [3.80] Upper lowerbound for aiodns to fix hanging issue
  pyproject.toml
Labels: no-issue, no-changelog

#6693 Test multithreaded file hashing
  CHANGES/+multithread-file-hashing.feature
  pulpcore/app/files.py
  pulpcore/download/base.py
Labels: no-issue

#6722 Add a python version to pycares constraint
  pyproject.toml
Labels: backport-3.49, no-issue, no-changelog, backport-3.63

#6724 Add a python version to pycares constraint
  requirements.txt
Labels: no-issue, no-changelog
