Repository pulp/pulpcore, pull requests merged in 2025-01, with the labels that each got.

#6179 Update jinja2 requirement from <=3.1.4,>=3.1 to >=3.1,<=3.1.5
  requirements.txt
Labels: backport-3.22, backport-3.39, backport-3.49, no-issue, no-changelog

#6182 Update jinja2 requirement from <=3.1.4,>=3.1 to >=3.1,<=3.1.5
  requirements.txt
Labels: no-issue, no-changelog

#6183 Fix bad file test fixture server
  pulp_file/pytest_plugin.py
Labels: backport-3.49

#6188 Update jinja2 requirement from <=3.1.4,>=3.1 to >=3.1,<=3.1.5
  requirements.txt
Labels: no-issue, no-changelog

#6189 [PULP-250] Fix typo in task state logic
  pulpcore/app/models/task.py
Labels: backport-3.39, backport-3.49, no-issue, no-changelog, backport-3.63, backport-3.69

#6192 Quiet a lint warning about improper flag usage
  pulp_certguard/tests/functional/artifacts/x509/gensrv.sh
Labels: no-issue, no-changelog, backport-3.63, backport-3.69

#6216 Patchback/backports/3.63/3e8b765525916406304279f2b071220c62a2e02b/pr 6211
  pyproject.toml
  requirements.txt
Labels: no-issue, no-changelog

#6217 Fix links and re-add pulp-101 image
  CODE_OF_CONDUCT.md
  README.md
  docs/assets/images/pulp-101.png
  docs/user/tutorials/index.md
  pulpcore/app/models/replica.py
  pulpcore/app/settings.py
  pulpcore/tests/functional/api/test_auth.py
Labels: no-issue, no-changelog

#6223 [PULP-296] Fixup running tasks that are not unblocked
  CHANGES/6225.bugfix
  pulpcore/tasking/worker.py
Labels: backport-3.49, backport-3.63, backport-3.69

#6158 [PULP-265] Add docs about STORAGES settings
  docs/admin/guides/_SUMMARY.md
  docs/admin/guides/configure-pulp/configure-storages.md
  docs/admin/guides/configure-pulp/index.md
  docs/admin/reference/settings.md
Labels: no-issue, no-changelog

#6240 Delete pulp_label_select field from UpstreamPulp
  CHANGES/plugin_api/+pulp_label_select.removal
  pulpcore/app/migrations/0127_remove_upstreampulp_pulp_label_select.py
  pulpcore/app/models/replica.py
Labels: no-issue

#6243 Update gitleaks to ignore example-keys.
  .gitleaks.toml
Labels: no-issue, no-changelog
