Repository pulp/pulpcore, pull requests merged in 2025-02, with the labels that each got.

#6252 Fix minor typo in documentation
  docs/dev/learn/tasks/add-remove.md
Labels: no-issue, no-changelog

#6253 Add pulp_created field as a task filter
  CHANGES/6241.feature
  pulpcore/app/viewsets/task.py
  pulpcore/tests/functional/api/test_tasking.py
Labels: no-issue

#6272 Add LIMIT statement to those queries needed during Pulp startup process.
  pulpcore/app/settings.py
Labels: no-issue, no-changelog

#6292 Fix a FileNotFound err with tmpDir in immediate tasks
  pulpcore/tasking/tasks.py
Labels: no-issue, no-changelog

#6294 Change workdir even if the immediate task fails
  CHANGES/6293.bugfix
  pulpcore/tasking/tasks.py
Labels: backport-3.71

#5832 Optimize ACS pipeline for runtime and memory
  CHANGES/+acs-optimization.bugfix
  pulpcore/plugin/stages/artifact_stages.py
  pulpcore/plugin/stages/declarative_version.py
Labels: multi-commit, no-issue, no-changelog

#6305 Revert "Use openapi 3.1.0 for schema generation"
  pulpcore/app/settings.py
  pulpcore/tests/functional/api/test_openapi_schema.py
Labels: no-issue, no-changelog, backport-3.72

#6311 Allow use of pulp-glue/0.31.
  requirements.txt
Labels: no-issue, no-changelog

#6310 Add a new doc about how to use AWS CloudFront as backend storage.
  CHANGES/6258.doc
  docs/admin/guides/configure-pulp/configure-storages.md
  pulpcore/tests/unit/serializers/test_domain.py
Labels: no-issue

#6308 Fix plugin defaults overriding user settings
  CHANGES/+default-plugin-settings.bugfix
  pulpcore/app/settings.py
Labels: no-issue
