Repository pulp/pulpcore, pull requests merged in 2025-03, with the labels that each got.

#6320 [PULP-296] Fix an issue with a previous patch for tasks not marked unblocked
  CHANGES/6225.misc
  pulpcore/tasking/worker.py
Labels: backport-3.49, backport-3.63

#6327 Added 3.73 to 'supported_release_branches'.
  template_config.yml
Labels: no-issue, no-changelog

#6331 Revert "Allow to specify the type of remote authentication"
  .github/template_gitref
  .github/workflows/scripts/install.sh
  CHANGES/+revert-5438.bugfix
  CHANGES/5437.feature
  docs/admin/reference/settings.md
  pulpcore/app/settings.py
  pulpcore/openapi/__init__.py
  pulpcore/tests/functional/api/test_auth.py
  pulpcore/tests/functional/api/test_openapi_schema.py
  template_config.yml
Labels: no-issue, backport-3.73

#6336 Fixed a conflicting-migration problem with 0130 migration(s).
  pulpcore/app/migrations/0131_distribution_checkpoint_publication_checkpoint.py
Labels: no-issue, no-changelog

#6346 Bump jinja2 to 3.1.6
  pyproject.toml
Labels: no-issue, no-changelog, backport-3.73

#6347 Bump jinja2 3.63
  requirements.txt
Labels: backport-3.39, backport-3.28, backport-3.49, no-issue, no-changelog

#6339 Fixed a typo in the tech-preview doc.
  docs/admin/reference/tech-preview.md
Labels: no-issue, no-changelog

#6350 Optimize ACS pipeline [3.39]
  CHANGES/+acs-optimization.bugfix
  pulpcore/plugin/stages/artifact_stages.py
  pulpcore/plugin/stages/declarative_version.py
Labels: multi-commit, no-issue, no-changelog

#6349 Optimize ACS pipeline [3.49]
  CHANGES/+acs-optimization.bugfix
  pulpcore/plugin/stages/artifact_stages.py
  pulpcore/plugin/stages/declarative_version.py
Labels: multi-commit, no-issue, no-changelog

#6348 Optimize ACS pipeline [3.63]
  CHANGES/+acs-optimization.bugfix
  pulpcore/plugin/stages/artifact_stages.py
  pulpcore/plugin/stages/declarative_version.py
Labels: multi-commit, no-issue, no-changelog

#6345 [Docs] Improve admin configuration pages
  docs/admin/guides/configure-pulp/configure-storages.md
  docs/admin/guides/configure-pulp/index.md
  docs/admin/reference/settings.md
Labels: no-issue, no-changelog

#6338 Fixed set/unset_label API RBAC - now comes with a new permission.
  CHANGES/6337.bugfix
  CHANGES/6340.bugfix
  docs/user/guides/manage-labels.md
  pulp_file/app/viewsets.py
  pulp_file/tests/functional/api/test_content_labels.py
  pulpcore/app/global_access_conditions.py
  pulpcore/app/migrations/0132_alter_content_options.py
  pulpcore/app/models/content.py
  pulpcore/app/serializers/base.py
  pulpcore/app/viewsets/content.py
Labels: backport-3.73

#6367 Fix 401 error on domain's set/unset label
  CHANGES/+set-domain-label.bugfix
  pulpcore/app/viewsets/domain.py
  pulpcore/tests/functional/api/test_crud_domains.py
Labels: no-issue

#6376 Fixed 0131 and 0132 migrations to allow upgrading from 3.73.
  CHANGES/6375.bugfix
  pulpcore/app/migrations/0131_distribution_checkpoint_publication_checkpoint.py
  pulpcore/app/migrations/0132_alter_content_options.py
Labels: backport-3.74

#6373 documenting domain enabled apis
  docs/dev/learn/domains/domain_enabled_api.md
Labels: multi-commit, no-issue, no-changelog

#6383 Update logo url in openapi docs
  pulpcore/openapi/hooks.py
Labels: no-issue, no-changelog

#6155 [PULP-218] Add timeout to immediate tasks
  CHANGES/plugin_api/5930.bugfix
  pulpcore/app/tasks/base.py
  pulpcore/app/tasks/test.py
  pulpcore/app/viewsets/base.py
  pulpcore/constants.py
  pulpcore/pytest_plugin.py
  pulpcore/tasking/tasks.py
  pulpcore/tests/functional/api/test_tasking.py
Labels: no-issue

#6384 Fixed task purge when no user can be infered
  CHANGES/6380.bugfix
  pulpcore/app/tasks/purge.py
  pulpcore/app/util.py
  pulpcore/app/viewsets/task.py
Labels: backport-3.73, backport-3.74

#6412 Fix grouping for admin guides in docs
  docs/admin/guides/_SUMMARY.md
Labels: no-issue, no-changelog

#6413 [PULP-238] Fix remote timeout configuration
  CHANGES/5439.bugfix
  pulpcore/download/factory.py
Labels: no-issue
